name: Lint

on:
  push:
    branches: [main]
  pull_request:
  workflow_call:
    inputs:
      repository:
        default: Retiblo/Retiblo_nextjs
        required: false
        type: string

env:
  NODE_VERSION: 21.6.1

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository || github.repository }}
          submodules: recursive
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
      - run: bun run lint
      - name: Ensure a clean working directory
        run: git diff --name-status --exit-code
